#!/usr/bin/env zsh

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~ ~/Desktop ~/Desktop/cs334 ~/Desktop/cs511 ~/Desktop/cs382/grading ~/Desktop/cs382 -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

cd $selected
